# traefik.toml (静态配置)
[entryPoints]
  [entryPoints.web]
    address = ":7777"
  [entryPoint.traefik]
    address = ":8080"


[api]
  dashboard = true
  insecure = true

[log]
  level = "DEBUG"

[accessLog]
  filePath = "logs/access.log"

# [providers.file]
#   filename = "/dynamic.toml"
#   watch = true

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  network = "app-net"
  exposedByDefault = false